name: Delete Taurus Stack - Development

on:
    workflow_dispatch:

jobs:
  taurus-delete:
    name: taurus-delete-dev
    runs-on: ubuntu-latest
    environment:
        name: devl
        url: https://soa-training-aws-general.signin.aws.amazon.com/console
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - name: Checkout Code Repo
      uses: actions/checkout@v3

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Run npm ci 
      run: npm ci

    - name: Delete Taurus stack from Devlopment
      uses: serverless/github-action@v3.2
      with:
        args: -c "serverless remove --stage devl"
        entrypoint: /bin/sh
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}