name: "Deploy Taurus Stack - Development"

on:
    push:
        branches:
        - main
    workflow_dispatch:

jobs:
  taurus-deploy:
    name: taurus-deploy-dev
    runs-on: ubuntu-latest
    environment:
        name: devl
        url: https://soa-training-aws-general.signin.aws.amazon.com/console
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - name: Checkout Code Repo
      uses: actions/checkout@v3

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Create Lambda Layer Library Directory
      run: mkdir -p ./code/layer/

    - name: Zip the Folder Containing my_lib.py 
      run: zip -r ./code/layer/my_lib.zip ./code/python/my_lib.py

    - name: Run npm ci 
      run: npm ci

    - name: Deploy Taurus stack to Devlopment
      uses: serverless/github-action@v3.2
      with:
        args: -c "serverless deploy --stage devl"
        entrypoint: /bin/sh
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}